# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
cran: http://cran.rstudio.com/

env:
  global:
    - secure: "KxcKSH4TFMbNMKAj6ePl4yq6SCeYQJcDkw0PMuEdImomwxqY3mP8p+GWVmNN1PKl8k7C/rgLNPAiBoJmddXMzFvGoGRWvyeER0lDN49rzNPHANF9wnMBBYN27mp98hBZlX2Vxu48M3jbmy+wRpmKKvKxTxOa8tUkt0GVEUTPeGQ="

before_install:
  - tlmgr install xcolor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile
  - "chmod 755 ./_push_vignettes.sh"

r_build_args: " "

r_check_args: "--as-cran"

warnings_are_errors: true

r_binary_packages:
  - chron
  - circstats
  - colorspace
  - data.table
  - dichromat
  - digest
  - dplyr
  - ggplot2
  - gtable
  - httr
  - igraph
  - knitr
  - labeling
  - latticeextra
  - lubridate
  - magrittr
  - munsell
  - proto
  - randomfields
  - raster
  - rcolorbrewer
  - rcpp
  - reshape
  - rgdal
  - scales
  - secr
  - snow
  - sp
  - stringr
  - testthat
  - tkrplot
  - xts
  - zoo

r_github_packages:
  - s-u/fastshp
  - jimhester/covr
  - rich-iannone/DiagrammeR
  - MangoTheCat/visualTest

after_success:
  - ./_push_vignettes.sh
  - Rscript -e 'library(covr); coveralls(coverage = print(package_coverage(quiet = FALSE))); devtools::session_info()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
